### ISSUE TITLE
Deleted project does not cascade delete builds

### ISSUE THREAD

**Issue by jwilm** [cobyism/dciy#24]
Visiting `builds_path` after destroying a project which had generated builds results in a **NoMethodError**. In the Builds#index view, it tries to access `build.project.repo` which raises an error when trying to call `repo` on the undefined `build.project`.

I think it makes sense to cascade the destroy action to builds attached to the project. We can accomplish with a small migration - needs regression test.

**Comment by cobyism** [comment]
Good catch—this should just need a `:dependent => :destroy` parameter set up [on the relationship](https://github.com/cobyism/dciy/blob/master/app/models/project.rb#L2).
