### ISSUE TITLE
DCIY should be tested itself

### ISSUE THREAD

**Issue by cobyism** [cobyism/dciy#7]
I’ve just been build this up from scaffolds, and this project really needs a test suite of it’s own. Bonus points if DCIY can be set up to build itself as a special-case part of the UI or something to make hacking on it easier (i.e. while the dev server is running). Recursion is awesome.

**Comment by smashwilson** [comment]
Any objections to RSpec? `rspec-mocks` is built-in and pretty handy for stubbing out things like the `Runner`. Of course, it's one more external dependency, and there are other mocking frameworks that can integrate with `Test::Unit` if you'd rather go that way.

**Comment by cobyism** [comment]
@smashwilson I’ve only ever really dealt with `Test::Unit` in my limited testing experience, so I’d be totally happy to learn about something new (RSpec). :+1:

**Comment by cobyism** [comment]
This is pretty much covered (at least to start with) after #15
